import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import Layout from "../../components/Layout";
import ProfileNav from "../../components/ProfileNav";
import UserCard from "../../components/UserCard";
import { ProfileRoutes } from "../../types/types";
import { trpc } from "../../utils/trpc";

const Following: NextPage = () => {
  const { data: session } = useSession();
  const following = trpc.follow.getFollowing.useQuery().data;

  return (
    <>
      <Head>
        <title>Gamr.app | Following</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {session && (
          <main className="container mx-auto grid grid-cols-3 gap-y-2 p-4">
            <div className="col-span-2 col-start-2">
              <ProfileNav />
            </div>
            <div>
              {following?.map(({ user }) => {
                return (
                  <Link
                    href={`${ProfileRoutes.Profile}/${user.id}`}
                    key={user.id}
                  >
                    <a>
                      <UserCard user={user} following={true} />
                    </a>
                  </Link>
                );
              })}
            </div>
          </main>
        )}

        {!session && <main></main>}
      </Layout>
    </>
  );
};

export default Following;
