import { useEffect, useState } from "react";

import { User } from "@prisma/client";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

import Layout from "../../components/Layout";
import ProfileNav from "../../components/ProfileNav";
import UserCard from "../../components/UserCard";
import { trpc } from "../../utils/trpc";

const Following: NextPage = () => {
  const { data: session } = useSession();
  const [following, setFollowing] = useState<{ user: User }[]>();
  const getFollowing = trpc.follow.getFollowing.useQuery();

  useEffect(() => {
    const following = getFollowing.data;

    if (!following) {
      return;
    }

    setFollowing(following);
  }, [getFollowing.data]);

  return (
    <>
      <Head>
        <title>Gamr.app | Following</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {session && (
          <main className="container mx-auto grid grid-cols-3 gap-y-2 p-4">
            <div className="col-span-2 col-start-2">
              <ProfileNav />
            </div>
            <div>
              {following?.map((following) => {
                return (
                  <UserCard key={following.user.id} user={following.user} />
                );
              })}
            </div>
          </main>
        )}

        {!session && <main></main>}
      </Layout>
    </>
  );
};

export default Following;
