import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";


import Layout from "../components/Layout";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Gamr.app | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {session && (
          <main className="container mx-auto grid grid-cols-3 gap-y-2 p-4">
            Home Page
          </main>
        )}

        {!session && <main>Not signed in</main>}
      </Layout>
    </>
  );
};

export default Home;
